// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpXOkoFL_XndRf5m91LX_EeDl_B3z7-_Q',
    appId: '1:1005662102120:web:fe851b7cb453a0a74811dd',
    messagingSenderId: '1005662102120',
    projectId: 'ecommerseapp-5b73a',
    authDomain: 'ecommerseapp-5b73a.firebaseapp.com',
    storageBucket: 'ecommerseapp-5b73a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo5ifWHlM_larv48pSV_jp_ypnmbvulb0',
    appId: '1:1005662102120:android:4ed86decfc9401e44811dd',
    messagingSenderId: '1005662102120',
    projectId: 'ecommerseapp-5b73a',
    storageBucket: 'ecommerseapp-5b73a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyKWsEPyxmtDGqZnpTXOVIOHOh_A29YGI',
    appId: '1:1005662102120:ios:fa6516883b5827984811dd',
    messagingSenderId: '1005662102120',
    projectId: 'ecommerseapp-5b73a',
    storageBucket: 'ecommerseapp-5b73a.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyKWsEPyxmtDGqZnpTXOVIOHOh_A29YGI',
    appId: '1:1005662102120:ios:fa6516883b5827984811dd',
    messagingSenderId: '1005662102120',
    projectId: 'ecommerseapp-5b73a',
    storageBucket: 'ecommerseapp-5b73a.appspot.com',
    iosBundleId: 'com.example.musicApp',
  );
}
